title: Tabaré Capitán
description: Personal website - Economist
theme: just-the-docs



url: https://tabarecapitan.github.io/tabarecapitan.github.io


# logo: "/assets/images/logoTC.png"


# Google Analytics
google_analytics: "G-5XPBJKXZNK,UA-101029789-1"
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)



# External navigation links
nav_external_links:
  - title: my CV
    url: https://www.tabarecapitan.com/assets/cv/tabareCapitan_CV.pdf
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: google scholar
    url: https://scholar.google.com/citations?user=uqivDeoAAAAJ&hl=en
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: linkedIn
    url: https://www.linkedin.com/in/tabareCapitan/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    
    
    
# Aux links for the upper right navigation
aux_links:
  "🧠 Behavioral":
#     - "//github.com/just-the-docs/just-the-docs"
  "🌱 Environmental":
#     - "//github.com/just-the-docs/just-the-docs"
  "🌎 Development":
#     - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false



# grey-lt, grey-dk, purple, blue, green, yellow, and red are available
callouts:
  warning:
    title: 
    color: red
  
   morado:
    title: 
    color: purple
