title: Tabaré Capitán
description: personal website
theme: just-the-docs


url: https://tabarecapitan.github.io/tabarecapitan.github.io


# logo: "/assets/images/logoTC.png"


# Google Analytics
google_analytics: G-5XPBJKXZNK
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)


# External navigation links
nav_external_links:
#  - title: my CV
#    url: https://www.tabarecapitan.com/assets/cv/tabareCapitan_CV.pdf
#    hide_icon: false # set to true to hide the external link icon - defaults to false
#  - title: resume
#    url: https://www.tabarecapitan.com/assets/cv/tabareCapitan_resume.pdf
#    hide_icon: false # set to true to hide the external link icon - defaults to false
#  - title: google scholar

     
# Aux links for the upper right navigation
aux_links:
  "GitHub":
     - "//github.com/tabareCapitan/"
  "LinkedIn":
     - "//linkedin.com/in/tabareCapitan/"     
#  "Substack":
#     - "//tabarecapitan.substack.com/"


     
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


callouts_level: quiet # or loud
callouts:
  highlightPurple:
    color: purple
  highlightGray:
    color: grey-lt
  highlightRed:
    color: red
  highlightGreen:
    color: green
  highlightYellow:
    color: yellow     
  highlightBlue:
    color: blue      
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
