title: Tabaré Capitán
description: Personal website - Economist
theme: just-the-docs

url: https://tabarecapitan.github.io/tabarecapitan.github.io

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-5555555-55
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

# External navigation links
nav_external_links:
  - title: CV
    url: https://github.com/tabareCapitan/tabarecapitan.github.io/blob/main/assets/cv/tabareCapitan_CV.pdf
    hide_icon: false # set to true to hide the external link icon - defaults to false
