---
format:
  html:
    toc: true
    toc-location: right
---


# Introduction

I find it useful to see what tools and software people use, so here is mine.

In general, I prefer tools that are cross-platform, simple, and not tied to a single ecosystem. When it makes sense, I use open-source software like Linux. Other times I use proprietary tools like Gmail or Workflowy because they fit my needs better.

If a tool needs funding to sustain development or to cover variable costs, I prefer to pay for it directly. That feels more transparent than relying on indirect models, though in practice I use a mix of free and paid tools depending on the case.

Most of my time is spent writing in two places: [VS Code](https://code.visualstudio.com/) for code, and [Obsidian](https://obsidian.md/) for everything else. I use the [Catppuccin](https://catppuccin.com/) theme in both, which gives me a consistent dark interface that is easy on the eyes.

This page will likely grow as I add or change tools.


# Browser

I use [Brave](https://brave.com) as my main browser, primarily for its built-in privacy features. It also makes it easy to disable extras like VPN, LeoAI, and crypto wallet integrations, keeping the browser lean. 

Here are some extensions that I find useful: [SingleFile](https://github.com/gildas-lormeau/SingleFile) for saving complete webpages offline, [Obsidian Web Clipper](https://github.com/obsidianmd/obsidian-clipper) to send content directly into my (Obsidian) vault, [Zotero Connector](https://www.zotero.org/download/connectors) for capturing references and metadata, the [Google Scholar Button](https://scholar.google.com/intl/en/scholar/help.html#button) for quick access to papers and citations, and [Unpaywall](https://unpaywall.org/products/extension) to find legal open-access versions of academic articles.


# Focus (music)

I often work with background music, especially for deep focus. "Regular" music works, but it can also become a distraction on its own, either because it is too engaging or because of track changes. Classical and other lyric-free music works well. I mostly use [Brain.fm](https://www.brain.fm/), which claims to create music that is "purpose-built to steer you into a desired mental state". I haven't read the research, but it is supposed to have some [real science](https://www.brain.fm/science) behind it. All I can say is that it has been good for me. The "purpose-built" part also seems to work beyond deep focus, with modes for learning, creativity, chill, unwind, destress, sleep, and more. 

I still use it every day, but I have three issues with Brain.fm: no real desktop app (they only just released one for Mac), it's hard to tell when (and if) new material comes out, and the price feels too high. On the last point, services like Spotify and Youtube Music return about 60-70% of revenue to right holders, while Brain.fm produces its own catalogue. Intellectual property rights don't enter as a variable cost in the same way; it seems closer to a one-time cost to create tracks. I don't know how expensive it is to make music for Brain.fm, but it's almost certainly far cheaper than producing commercial songs. Yet the pricing doesn't reflect those different cost structures. As of August 2025 in Sweden, you pay about USD 13.5/month for Spotify, USD 12.5/month for Youtube Music, and USD 10/month for Brain.fm (USD 5.8 if billed annually). 


# IDE + Text editor

[VS Code](https://code.visualstudio.com/), all the way. I use it for all my coding, which includes [Python](https://www.python.org/), [Stata](https://www.stata.com/) (with [Stata Enhanced](https://marketplace.visualstudio.com/items?itemName=kylebarron.stata-enhanced) and [StataRun](https://marketplace.visualstudio.com/items?itemName=Yeaoh.stataRun)), and [R](https://www.r-project.org/). I use it to build this website via [Quarto](https://quarto.org/). And I also use it for typesetting in [LaTeX](https://www.latex-project.org/). [Git](https://git-scm.com/) for version control, with [GitHub](https://github.com/) as the remote. I also use [GitHub Copilot](https://github.com/features/copilot) when it helps.

In the past I used [Sublime](https://www.sublimetext.com/), which remains a great lightweight text editor, but I prefer to have everything in one place. Before that, I had a good run with [Atom](https://atom-editor.cc/) (deceased).


# Mail

I use [Gmail](http://gmail.com) with three extensions: [Simplify](https://simplify.email/) for a cleaner interface and lots of features, [Inbox When Ready](https://inboxwhenready.org/) to hide the inbox when I don't want to see it, and [TeX for Gmail](https://chrome.google.com/webstore/detail/tex-for-gmail/egkbleipdnmlndoaapdppmeajkkigddo) when I need to include equations. 


# Note-taking


I use [Obsidian](https://obsidian.md/) to write everything (except [code](#ide-text-editor)) that I want to keep: papers, ideas, recipes, health notes, things I learn, and more. 

I added a few community plugins to Obsidian to make it more useful: [Better Word Count](https://obsidian.md/plugins?id=better-word-count), [Dataview](https://blacksmithgu.github.io/obsidian-dataview/), [Go to Heading](https://obsidian.md/plugins?id=gotoheading), [Hider](https://obsidian.md/plugins?id=obsidian-hider), [Homepage](https://obsidian.md/plugins?id=homepage), [LaTeX Suite](https://obsidian.md/plugins?id=latex-suite), [Pandoc](https://obsidian.md/plugins?id=obsidian-pandoc), [Quick Switcher++](https://obsidian.md/plugins?id=quick-switcher-plus-plus), [QuickAdd](https://obsidian.md/plugins?id=quickadd), [Remember Cursor Position](https://obsidian.md/plugins?id=remember-cursor-position), [Templater](https://obsidian.md/plugins?id=templater-obsidian), [Text Snippets](https://obsidian.md/plugins?id=text-snippets), [TTS](https://obsidian.md/plugins?id=text-to-speech), [Typewriter Scroll](https://obsidian.md/plugins?id=typewriter-scroll), and [Zotero Integration](https://github.com/mgmeyers/obsidian-zotero-integration). 

Obsidian is flexible. You can make it look and act however you want. The [developers](https://obsidian.md/about) are active and reasonable. The [community](https://docs.obsidian.md/Home) builds and maintains a huge set of plugins. The [roadmap](https://obsidian.md/roadmap) is transparent. It isn’t open-source, but it has regular audits and a feasible business model, which gives me confidence in using it long term. The business model is simple: you only pay if you want sync or publishing. Because it’s funded directly by users,  development can stay focused on product rather than outside pressures. Most importantly, notes stay in plain text Markdown files (see [File over app](https://stephango.com/file-over-app)). That means no lock-in.


# Organization

I use [Workflowy](https://workflowy.com/) for text that is meant to disappear: shopping lists, to-do lists, travel itineraries, and more. It’s a simple, fast, and flexible outliner that works well for quick notes and lists. I mostly like it because it is so simple and I can easily use it without touching my mouse. It's been my main planning tool for a while.


# OS

My main OS is [Fedora](https://fedoraproject.org/) (Linux), which provides modern kernels and software alongside a clean upstream GNOME experience. Although somewhat sponsored by IBM through its Red Hat ties, development remains [credibly independent](https://en.wikipedia.org/wiki/Fedora_Project). [Ubuntu](https://ubuntu.com/) is convenient and user-friendly, though I prefer Fedora’s approach over Canonical’s Snap ecosystem. [Linux Mint](https://www.linuxmint.com/) attempts to "clean" Ubuntu but still relies on Canonical dependencies. I have no concerns about [Debian](https://www.debian.org/), but it may be too conservative for my needs.

I also keep [Windows](https://www.microsoft.com/en-gb/windows/) (dual-boot with GRUB) for a few applications that lack Linux support, such as [Garmin Express](https://www.garmin.com/sv-SE/software/express/windows/) and [BankID](https://www.bankid.com/en/). 


# Sync and storage

I use [Nextcloud](https://nextcloud.com/) for file sync, hosted on [Hetzner Storage Share](https://www.hetzner.com/storage/storage-share/) (Hosted in the EU). It is a bit more complex to set up than alternatives like Dropbox, but it gives you so much  control and flexibility for a fraction of the monthly cost (~20% of the current price of Dropbox for two users).

Nextcloud is open-source, so it can run on a self-hosted server or on any third-party provider. It has a large community and many plugins to extend its functionality. I do not use any of the Nextcloud apps, but I do use the [Nextcloud Desktop Client](https://docs.nextcloud.com/desktop/latest/) to sync files across devices. Once setup is done, it works seamlessly in the background. [Virtual File System](https://help.nextcloud.com/t/how-do-virtual-files-work-in-the-client/154234) (VFS) works well in Windows, although it is better to keep a separate sync folder with VFS enabled. As of August 2025, VFS does not work in Linux, but it is easy to mount a remote folder with [WebDAV](https://en.wikipedia.org/wiki/WebDAV).


# Website

This site is built with [Quarto](https://quarto.org/), rendered locally, and deployed via [GitHub Pages](https://pages.github.com/). Quarto handles the formatting and publishing workflow in Markdown and integrates directly with VS Code, which makes editing and updating simple.
