name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false

      - name: Clear runner cache
        run: sudo rm -rf /home/runner/.cache
      
      - name: Install dependencies and update Gemfile.lock
        run: |
          bundle config --local deployment false
          bundle config unset path || true
          bundle install
          if [[ -n $(git status --porcelain Gemfile.lock) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add Gemfile.lock
            git commit -m "Update Gemfile.lock to match Gemfile"
            git push
          fi

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
